import Sidebar from "@/components/Sidebar";
import { inter } from "./fonts";
import "./globals.css";

export const metadata = {
  title: "Swift",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex text-gray-800 dark:text-gray-200`}>
        <Sidebar />
        <main className="p-7 flex-1 text-2xl font-semibold h-screen bg-gray-200 dark:bg-gray-900">{children}</main>
      </body>
    </html>
  );
}
